import { Inter } from "next/font/google";
import "./globals.css";
import styles from "../../tetfund/public/styles/layout.module.css";
import Navbar from "./components/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.layoutParent}>
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
